TALLER1 = {"ANA", "CARLOS", "JAVIER", "LUCIA"}
TALLER2 = {"LUCIA", "MARIA", "CARLOS", "MIGUEL"}
TALLER3 = {"ANA", "JAVIER", "JOSE", "MIGUEL"}

REPETIDOS = (TALLER1 & TALLER2) | (TALLER2 & TALLER3) | (TALLER1 &  TALLER3)
print("LOS ALUMNOS QUE SE ENCUENTRAN INSCRITOS EN MAS DE UN TALLER SON:")
print(REPETIDOS)